### ISSUE TITLE
Non-Linear Analysis

### ISSUE THREAD

**Issue by ajos6183** [epsi1on/BFE.Net#2]
Hi Ehsan,

I noticed that your finite element analysis project is one of the few ones in C# on the web and you seem to have good knowledge in this field. Would i be able to contact you with a question?

I am working on a non-Linear Geometric Analysis package for 3D beams and i can share some of my code with you.

Regards,
Anthony

**Comment by epsi1on** [comment]
Hi Anthony,
Thanks for your writing.
I think it is very good idea, and we can make another package that do nonlinear geometric analysis (for beam element probably). but first i need to ask questions:
After solving model, we will find a displacement vector ok? for nonlinear geometric analysis, how beam element internal force are computed? is it same as linear analysis? (D.B.U matrix multiplication?)
Thanks

**Comment by ajos6183** [comment]
Hi Ehsan,

I ended up just doing a simple non-linear analysis for small displacements and with no geometry update.
I am using the Euler-Bernoulli theory and then adding a geometric stiffness matrix such as the one on page 257 of [this book](http://digitalcommons.bucknell.edu/books/7/).

Essentially, the stiffness matrix has two terms. The first is the elastic component which the exact same thing as the linear stiffness matrix. The second is the geometric component which depends on the axial forces in the members.

Anthony
